#!/usr/bin/env python3
"""
Verify the committed IRP outputs and, optionally, a full local reproduction.

Quick mode uses only Python's standard library and checks the frozen
configuration plus committed result artefacts.

Full mode additionally checks the exact locked Python environment and the
Git-ignored intermediate files that are regenerated by notebooks 01-06.
"""

from __future__ import annotations

import argparse
import ast
import csv
import importlib.metadata
import math
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RESULT_TABLES = ROOT / "results" / "tables"
SAMPLES = ROOT / "data" / "samples"

EXPECTED_DATASET_REVISION = "200748d9d3cddcc9d782887541057aca0b18c5da"


class CheckRunner:
    def __init__(self) -> None:
        self.failures: list[str] = []

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            print(f"PASS  {label}")
            return

        suffix = f" — {detail}" if detail else ""
        print(f"FAIL  {label}{suffix}")
        self.failures.append(label)

    def close(self) -> int:
        print("\n" + "=" * 72)
        if self.failures:
            print(f"REPRODUCTION VERIFICATION FAILED ({len(self.failures)} check(s))")
            print("=" * 72)
            for failure in self.failures:
                print(f"- {failure}")
            return 1

        print("REPRODUCTION VERIFICATION PASSED")
        print("=" * 72)
        return 0


def read_constant(path: Path, name: str) -> Any:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                if isinstance(target, ast.Name) and target.id == name:
                    value = node.value
                    return ast.literal_eval(value)
    raise KeyError(f"{name} not found in {path}")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def count_csv_rows(path: Path) -> int:
    """Count logical CSV records, including files with embedded newlines."""
    return len(read_csv(path))


def parse_binary(value: Any) -> int:
    """Parse common CSV encodings of boolean/binary values as 0 or 1."""
    text = str(value).strip().lower()

    if text in {"1", "1.0", "true", "t", "yes"}:
        return 1
    if text in {"0", "0.0", "false", "f", "no", ""}:
        return 0

    try:
        numeric = float(text)
    except ValueError as exc:
        raise ValueError(f"Could not parse binary value: {value!r}") from exc

    if numeric == 1.0:
        return 1
    if numeric == 0.0:
        return 0

    raise ValueError(f"Expected binary value, got: {value!r}")


def float_close(actual: Any, expected: float, tolerance: float = 5e-4) -> bool:
    try:
        return math.isclose(float(actual), expected, abs_tol=tolerance, rel_tol=0.0)
    except (TypeError, ValueError):
        return False


def select_row(
    rows: list[dict[str, str]],
    **criteria: str,
) -> dict[str, str] | None:
    for row in rows:
        if all(row.get(key) == value for key, value in criteria.items()):
            return row
    return None


def verify_frozen_configuration(checks: CheckRunner) -> None:
    config = ROOT / "src" / "config.py"
    labelling = ROOT / "src" / "labelling.py"
    noise = ROOT / "src" / "noise.py"
    preprocessing = ROOT / "src" / "preprocessing.py"

    checks.check(
        "Dataset revision is pinned",
        read_constant(config, "DATASET_REVISION") == EXPECTED_DATASET_REVISION,
    )
    checks.check(
        "Random seed is 42",
        read_constant(config, "RANDOM_SEED") == 42,
    )
    checks.check(
        "Relevance filter is relevance_v1",
        read_constant(config, "FILTER_VERSION") == "relevance_v1",
    )
    checks.check(
        "Weak-label rules are disempowerment_weak_v5",
        read_constant(labelling, "WEAK_LABEL_VERSION")
        == "disempowerment_weak_v5",
    )
    checks.check(
        "Noise version is noise_v1",
        read_constant(noise, "NOISE_VERSION") == "noise_v1",
    )
    checks.check(
        "Eight frozen noise conditions are present",
        tuple(read_constant(noise, "NOISE_CONDITIONS"))
        == (
            "clean",
            "casing",
            "punctuation",
            "whitespace",
            "typo",
            "word_deletion",
            "filler",
            "mixed",
        ),
    )
    checks.check(
        "Preprocessing version is preprocess_v1",
        read_constant(preprocessing, "PREPROCESS_VERSION") == "preprocess_v1",
    )
    checks.check(
        "Four frozen preprocessing configurations are present",
        tuple(read_constant(preprocessing, "PREPROCESS_CONFIGS"))
        == ("none", "minimal", "noise_aware", "aggressive"),
    )


def verify_committed_results(checks: CheckRunner) -> None:
    required = [
        RESULT_TABLES / "pilot_ranking_summary.csv",
        RESULT_TABLES / "scaled_robustness_summary_32_conditions.csv",
        RESULT_TABLES / "scaled_directive_cue_retention_summary.csv",
        RESULT_TABLES / "scaled_oof_predictions_52256.csv",
        RESULT_TABLES / "final_pilot_vs_scaled_comparison.csv",
        RESULT_TABLES / "final_research_question_synthesis.csv",
    ]
    for path in required:
        checks.check(f"Result file exists: {path.name}", path.exists())

    if not all(path.exists() for path in required):
        return

    pilot = read_csv(RESULT_TABLES / "pilot_ranking_summary.csv")
    pilot_clean = select_row(
        pilot,
        noise_condition="clean",
        preprocess_config="none",
    )
    checks.check("Pilot clean+none row exists", pilot_clean is not None)
    if pilot_clean:
        checks.check(
            "Pilot clean mean-fold ROC-AUC ≈ 0.867",
            float_close(pilot_clean["mean_roc_auc"], 0.867),
        )
        checks.check(
            "Pilot clean mean-fold AP ≈ 0.537",
            float_close(pilot_clean["mean_average_precision"], 0.537),
        )

    scaled = read_csv(
        RESULT_TABLES / "scaled_robustness_summary_32_conditions.csv"
    )
    checks.check("Scaled robustness summary has 32 rows", len(scaled) == 32)

    clean = select_row(
        scaled,
        noise_condition="clean",
        preprocess_config="none",
    )
    checks.check("Scaled clean+none row exists", clean is not None)
    if clean:
        checks.check("Scaled sources = 1,633", int(clean["n"]) == 1633)
        checks.check("Scaled positives = 17", int(clean["positives"]) == 17)
        checks.check(
            "Default-threshold predicted positives = 0",
            int(clean["predicted_positives"]) == 0,
        )
        checks.check(
            "Clean pooled ROC-AUC ≈ 0.8628",
            float_close(clean["pooled_roc_auc"], 0.8628),
        )
        checks.check(
            "Clean pooled AP ≈ 0.1233",
            float_close(clean["pooled_average_precision"], 0.1233),
        )
        checks.check(
            "Clean mean-fold ROC-AUC ≈ 0.8729",
            float_close(clean["mean_fold_roc_auc"], 0.8729),
        )
        checks.check(
            "Clean mean-fold AP ≈ 0.1974",
            float_close(clean["mean_fold_average_precision"], 0.1974),
        )
        checks.check(
            "Clean confusion totals are TN=1616, FP=0, FN=17, TP=0",
            (
                int(clean["tn"]) == 1616
                and int(clean["fp"]) == 0
                and int(clean["fn"]) == 17
                and int(clean["tp"]) == 0
            ),
        )

    checks.check(
        "Scaled OOF table has 52,256 rows",
        count_csv_rows(RESULT_TABLES / "scaled_oof_predictions_52256.csv")
        == 52256,
    )

    cue_rows = read_csv(
        RESULT_TABLES / "scaled_directive_cue_retention_summary.csv"
    )
    aggressive = select_row(cue_rows, preprocess_config="aggressive")
    checks.check("Aggressive cue-retention row exists", aggressive is not None)
    if aggressive:
        checks.check(
            "Aggressive tracked directive cue retention = 0.0%",
            float_close(aggressive["any_cue_retention_pct"], 0.0, 1e-9),
        )
        checks.check(
            "Aggressive cue-retention denominator = 112 rows",
            int(aggressive["rows"]) == 112,
        )

    final_compare = read_csv(
        RESULT_TABLES / "final_pilot_vs_scaled_comparison.csv"
    )
    checks.check("Final pilot-vs-scaled synthesis has 2 rows", len(final_compare) == 2)

    rq = read_csv(RESULT_TABLES / "final_research_question_synthesis.csv")
    checks.check("Final RQ synthesis has 3 rows", len(rq) == 3)
    if rq:
        checks.check(
            "Final RQ synthesis contains RQ1, RQ2 and RQ3",
            {row.get("research_question") for row in rq}
            == {"RQ1", "RQ2", "RQ3"},
        )


def verify_lock_environment(checks: CheckRunner) -> None:
    lock = ROOT / "requirements-lock.txt"
    checks.check("requirements-lock.txt exists", lock.exists())
    if not lock.exists():
        return

    result = subprocess.run(
        [sys.executable, "-m", "pip", "check"],
        capture_output=True,
        text=True,
    )
    checks.check(
        "pip check reports no broken requirements",
        result.returncode == 0,
        (result.stdout + result.stderr).strip(),
    )

    mismatches: list[str] = []
    checked = 0

    for raw in lock.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "==" not in line:
            continue

        package, expected = line.split("==", 1)
        expected = expected.split(";", 1)[0].strip()
        package = package.strip()

        try:
            installed = importlib.metadata.version(package)
        except importlib.metadata.PackageNotFoundError:
            mismatches.append(f"{package}: expected {expected}, not installed")
            continue

        checked += 1
        if installed != expected:
            mismatches.append(
                f"{package}: expected {expected}, installed {installed}"
            )

    checks.check("Locked packages checked = 125", checked == 125)
    checks.check(
        "Installed package versions match requirements-lock.txt",
        not mismatches,
        "; ".join(mismatches[:5]),
    )


def verify_full_intermediates(checks: CheckRunner) -> None:
    expected_paths = {
        "inspection": SAMPLES / "lmsys_inspection_sample.csv",
        "validation": SAMPLES / "lmsys_relevance_manual_validation_200.csv",
        "pilot": SAMPLES / "lmsys_relevance_pilot_100.csv",
        "labelled_pilot": SAMPLES / "lmsys_disempowerment_weak_v5_pilot_100.csv",
        "pilot_matrix": SAMPLES / "lmsys_noise_preprocess_v1_matrix_3200.csv",
        "positive_audit": SAMPLES / "lmsys_full_weak_v5_positive_audit_56.csv",
        "negative_audit": SAMPLES / "lmsys_full_weak_v5_negative_audit_100.csv",
        "target": SAMPLES / "lmsys_full_audit_corrected_target_1633.csv",
        "scaled_matrix": SAMPLES / "lmsys_scaled_noise_preprocess_v1_matrix_52256.csv",
    }

    for label, path in expected_paths.items():
        checks.check(f"Intermediate exists: {label}", path.exists())

    if not all(path.exists() for path in expected_paths.values()):
        return

    checks.check(
        "Inspection sample has 25 rows",
        count_csv_rows(expected_paths["inspection"]) == 25,
    )

    validation = read_csv(expected_paths["validation"])
    checks.check("Manual relevance validation has 200 rows", len(validation) == 200)
    manual_values = [parse_binary(row.get("manual_relevant", "")) for row in validation]
    checks.check(
        "Manual relevance decisions are complete",
        len(manual_values) == len(validation),
    )
    relevant = sum(manual_values)
    checks.check("Manual relevance positives = 108", relevant == 108)
    checks.check("Manual relevance negatives = 92", len(validation) - relevant == 92)

    checks.check(
        "Final pilot has 100 rows",
        count_csv_rows(expected_paths["pilot"]) == 100,
    )

    labelled_pilot = read_csv(expected_paths["labelled_pilot"])
    checks.check("Weak-labelled pilot has 100 rows", len(labelled_pilot) == 100)
    if labelled_pilot:
        pilot_positive_count = sum(
            parse_binary(row.get("weak_label_any", "0"))
            for row in labelled_pilot
        )
        checks.check("Weak-labelled pilot positives = 6", pilot_positive_count == 6)

    checks.check(
        "Pilot noise/preprocessing matrix has 3,200 rows",
        count_csv_rows(expected_paths["pilot_matrix"]) == 3200,
    )

    positive_audit = read_csv(expected_paths["positive_audit"])
    checks.check("Positive audit has 56 rows", len(positive_audit) == 56)
    if positive_audit:
        valid = sum(
            parse_binary(row.get("manual_audit_valid", "0"))
            for row in positive_audit
        )
        checks.check("Positive audit valid detections = 16", valid == 16)
        checks.check("Positive audit false positives = 40", len(positive_audit) - valid == 40)

    negative_audit = read_csv(expected_paths["negative_audit"])
    checks.check("Negative audit has 100 rows", len(negative_audit) == 100)
    if negative_audit:
        missed = sum(
            parse_binary(row.get("manual_missed_positive", "0"))
            for row in negative_audit
        )
        checks.check("Negative audit missed positives = 1", missed == 1)

    target = read_csv(expected_paths["target"])
    checks.check("Audit-corrected target has 1,633 rows", len(target) == 1633)
    if target:
        sources = {row["source_index"] for row in target}
        positives = sum(parse_binary(row["target_label"]) for row in target)
        syc = sum(
            parse_binary(row["target_sycophantic_validation"])
            for row in target
        )
        over = sum(
            parse_binary(row["target_overconfident_judgement"])
            for row in target
        )
        directive = sum(
            parse_binary(row["target_directive_advice"])
            for row in target
        )

        checks.check(
            "Audit-corrected target has 1,633 unique sources",
            len(sources) == 1633,
        )
        checks.check("Audit-corrected target positives = 17", positives == 17)
        checks.check(
            "Audit-corrected target negatives = 1,616",
            len(target) - positives == 1616,
        )
        checks.check(
            "Corrected category totals are sycophantic=0, overconfident=1, directive=16",
            (syc, over, directive) == (0, 1, 16),
        )

    scaled_matrix = read_csv(expected_paths["scaled_matrix"])
    checks.check("Scaled matrix has 52,256 rows", len(scaled_matrix) == 52256)
    if scaled_matrix:
        sources = {row["source_index"] for row in scaled_matrix}
        conditions = {
            (row["noise_condition"], row["preprocess_config"])
            for row in scaled_matrix
        }
        positives = sum(
            parse_binary(row["target_label"])
            for row in scaled_matrix
        )
        checks.check(
            "Scaled matrix has 1,633 unique sources",
            len(sources) == 1633,
        )
        checks.check("Scaled matrix has 32 conditions", len(conditions) == 32)
        checks.check(
            "Scaled matrix has 544 positive-condition rows",
            positives == 544,
        )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Verify the IRP clean-room reproduction."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--quick",
        action="store_true",
        help="Check frozen configuration and committed results only (default).",
    )
    mode.add_argument(
        "--full",
        action="store_true",
        help="Also verify the locked environment and regenerated local intermediates.",
    )
    args = parser.parse_args()

    full = args.full

    print("=" * 72)
    print("IRP CLEAN-ROOM REPRODUCTION VERIFIER")
    print("=" * 72)
    print("Mode:", "FULL" if full else "QUICK")
    print("Repository:", ROOT)
    print()

    checks = CheckRunner()

    try:
        verify_frozen_configuration(checks)
        verify_committed_results(checks)
        if full:
            verify_lock_environment(checks)
            verify_full_intermediates(checks)
    except Exception as exc:
        checks.check(
            "Verifier completed without unexpected exceptions",
            False,
            repr(exc),
        )

    return checks.close()


if __name__ == "__main__":
    raise SystemExit(main())
